apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    env: development
spec:
  template:
    metadata:
      name: my-app
      labels:
        type: backend
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 3
